services:
  
  # This service should be able to scaffold a new Strapi project that can be built into an image
  # strapi-init:
  #   container_name: strapi-init
  #   image: node:lts-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "1337:1337"
  #   volumes:
  #     - ./image-lts-alpine:/opt/app
  #   command: npx --yes create-strapi-app@latest /opt/app --quickstart --no-run

  strapi:
    container_name: strapi
    build:
      context: ./app
      dockerfile: ../Dockerfile
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./app/config:/opt/app/config
      - ./app/src:/opt/app/src
      - ./app/package.json:/opt/package.json
      - ./app/package.lock.json:/opt/package.lock.json
      - ./app/types:/opt/app/types
      - ./app/uploads:/opt/app/public/uploads
      - ./app/dist:/opt/app/dist
    ports:
      - 1337:1337
    networks:
      - strapi
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    # platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: mysql:lts
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --mysql-native-password=ON   
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: strapi
    driver: bridge